site_name: Cogitator Documentation
site_description: Documentation for the Cogitator toolkit.
repo_url: https://github.com/habedi/cogitator
repo_name: habedi/cogitator

theme:
  name: readthedocs
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.top
    - navigation.indexes

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_source: true
nav:
  - Home: index.md
  - API Reference:
      - LLM Providers:
          - Base: api/model.md
          - OpenAI: api/openai.md
          - Ollama: api/ollama.md
      - Schemas: api/schemas.md
      - Embedding: api/embedding.md
      - Clustering: api/clustering.md
      - Strategies:
          - AutoCoT: api/auto_cot.md
          - CDWCoT: api/cdw_cot.md
          - GraphOfThoughts: api/graph_of_thoughts.md
          - LeastToMost: api/least_to_most.md
          - SelfConsistency: api/sc_cot.md
          - TreeOfThoughts: api/tree_of_thoughts.md
  - Benchmarking: benchmarks.md
  - Contributing: contributing.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true
